# Generated by Django 2.0.13 on 2019-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='meeting',
        ),
        migrations.AddField(
            model_name='participant',
            name='meeting',
            field=models.ManyToManyField(to='meetings.Meeting'),
        ),
    ]
