# Generated by Django 2.0.13 on 2019-05-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20190505_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='meeting',
            new_name='meetings',
        ),
    ]
